/*This file is generated by parse_dfa.c*/
#include"tm_lib.h"
#include"delta.h"
transition * delta(int state, char symbol){
transition * t = malloc(sizeof(transition));
switch(state){
case 0:
switch(symbol){
case 'a':
t->state = 1;
t->symbol = '_';
t->move = 1;
break;
case 'b':
t->state = 2;
t->symbol = '_';
t->move = 1;
break;
case '_':
t->move = ACCEPT;
break;
default:
t->move = ERROR;
break;
}
break;
case 1:
switch(symbol){
case 'a':
t->state = 1;
t->symbol = 'a';
t->move = 1;
break;
case 'b':
t->state = 1;
t->symbol = 'b';
t->move = 1;
break;
case '_':
t->state = 3;
t->symbol = '_';
t->move = 0;
break;
default:
t->move = ERROR;
break;
}
break;
case 2:
switch(symbol){
case 'a':
t->state = 2;
t->symbol = 'a';
t->move = 1;
break;
case 'b':
t->state = 2;
t->symbol = 'b';
t->move = 1;
break;
case '_':
t->state = 4;
t->symbol = '_';
t->move = 0;
break;
default:
t->move = ERROR;
break;
}
break;
case 3:
switch(symbol){
case 'a':
t->state = 5;
t->symbol = '_';
t->move = 0;
break;
case 'b':
t->move = REJECT;
break;
case '_':
t->move = ACCEPT;
break;
default:
t->move = ERROR;
break;
}
break;
case 4:
switch(symbol){
case 'b':
t->state = 5;
t->symbol = '_';
t->move = 0;
break;
case 'a':
t->move = REJECT;
break;
case '_':
t->move = ACCEPT;
break;
default:
t->move = ERROR;
break;
}
break;
case 5:
switch(symbol){
case 'a':
t->state = 5;
t->symbol = 'a';
t->move = 0;
break;
case 'b':
t->state = 5;
t->symbol = 'b';
t->move = 0;
break;
case '_':
t->state = 0;
t->symbol = '_';
t->move = 1;
break;
default:
t->move = ERROR;
break;
}
break;
default:
t->move = ERROR;
break;
}
return t;
}